version: "3"
services:
  api:
    build: 
      context: .
      dockerfile: ./Rooster.Api/Dockerfile
    ports: 
    - 80:5000
  worker:
    build: 
      context: .
      dockerfile: ./Rooster.Worker/Dockerfile
  redis:
    image: "redis:5"